# Struct Practice

## This notebook for praticing ***struct***, aka. constructors of Julia

### If you are coming from python, after classes and objects of python, constructors of Julia is a bit weird. Better practice!

In [4]:
# Set display width, load packages, import symbols
ENV["COLUMNS"]=72
using Pkg; for p in ("Knet","AutoGrad","IterTools","Plots","Images","ImageMagick"); haskey(Pkg.installed(),p) || Pkg.add(p); end
using Statistics: mean
using Base.Iterators: flatten
using IterTools: ncycle, takenth
import Random # seed!
using Knet: Knet, AutoGrad, dir, Data, Param, @diff, value, params, grad, progress, progress!, gpu, KnetArray, load, save
# The following are defined for instruction even though they are provided in Knet
# using Knet: accuracy, zeroone, nll, sgd

In [5]:
# Load data (mnistdata basically replicates mnist.ipynb)
include(Knet.dir("data","mnist.jl"))
dtrn,dtst = mnistdata(xsize=(784,:),xtype=Array)
println.(summary.((dtrn,dtst)));

600-element Data{Tuple{Array{Float32,2},Array{UInt8,1}}}
100-element Data{Tuple{Array{Float32,2},Array{UInt8,1}}}


## Linear Model Definition

In [18]:
struct Linear
    # Your code here
    w
    b
end

In [19]:
function Linear(xsize::Int, ysize::Int, atype=Array{Float64}, scale=0.1)
    # Your code here
    Linear(scale * randn(ysize,xsize),zeros(ysize))
end

Linear

In [20]:
model = Linear(13,1)

Linear([-0.12985205725626126 0.028599966494696285 … -0.22032975212883443 -0.07317727771927325], [0.0])

In [22]:
model.b

1-element Array{Float64,1}:
 0.0

In [23]:
function (l::Linear)(x)
    l.w*x.+l.b
end

In [26]:
pop = randn(13,1)

13×1 Array{Float64,2}:
 -0.17197782865103745
 -1.0979006335069137 
  1.4763069182699924 
  0.14679883271073682
  0.4793925403196781 
  0.5713952894483217 
  0.1138396720815193 
  0.3160470541581125 
  1.5706620949582497 
  0.5621225424436689 
 -1.1293957277018984 
  0.6883441416531069 
  0.07862750851664582

In [30]:
size([1 2 3; 4 5 6])

(2, 3)

In [27]:
model(pop)

1×1 Array{Float64,2}:
 -0.2545797938895558

In [ ]:
# In Julia we define a new datatype using `struct`:
struct Linear; w; b; end # I am declaring a new type, something called Linear! Each Linear has w and b of itself! 

# The new struct comes with a default constructor:
model = Linear(0.01 * randn(10,784), zeros(10)) # This is 'model', he is a Linear type! And here I am giving its w and b
                                                # its w is a random array of 10x784, and b is an array of 10 zeros


In [ ]:
# Alternative:

# We can define other constructors with different inputs:
Linear(i::Int,o::Int,scale=0.01) = Linear(scale * randn(o,i), zeros(o)) 
# on the above line: I am a "functionish" called Linear. It will take 2 integers and 1 float. 2 integers are input size and
# output size. for the mnist data, we have 784 input (features) and 10 outputs (10 classes). and scale is just an arbitary
# number for scaling our weights!

# This one allows instances to be defined using input and output sizes:
model = Linear(784,10)

In [ ]:
struct Linear
    # Your code here
    Param(w)
    Param(b)
end

function (l::Linear)(x)
    # Your code here
    w*x+b
end

function Linear(xsize::Int, ysize::Int, atype=Array{Float64}, scale=0.1)
    # Your code here
end

model = Linear(13, 1)